apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  ports: 80
   - port: 80
     targetport: 80
     name: http
  selector:
    app: webapp
  type: LoadBalancer
  ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
    replicas: 1
    template:
      metadata:
        labels:
          app: webapp
      spec:
        nodeSelector:
          "beta.kubernetes.io/os": windows
        containers:
        - name: dotnet-webapp
          image: imagename
          ports:
          - containerport: 80
